### ISSUE TITLE
解析 module-info.class 时发生 BufferUnderflowException

### ISSUE THREAD

**Issue by Glavo** [ClassViewer/ClassViewer#4]
module-info.java: 
```java
module hello {
    requires java.base;
    requires java.sql;
    requires java.xml;
}
```

```
java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Buffer.java:506)
	at java.nio.HeapByteBuffer.getShort(HeapByteBuffer.java:310)
	at org.glavo.viewer.BytesReader.readUnsignedShort(BytesReader.java:45)
	at org.glavo.viewer.classfile.datatype.UInt.readContent(UInt.java:44)
	at org.glavo.viewer.classfile.ClassFileComponent.read(ClassFileComponent.java:19)
	at org.glavo.viewer.classfile.ClassFileComponent.readContent(ClassFileComponent.java:31)
	at org.glavo.viewer.classfile.ClassFileComponent.read(ClassFileComponent.java:19)
	at org.glavo.viewer.classfile.datatype.Table.readEntry(Table.java:41)
	at org.glavo.viewer.classfile.datatype.Table.readContent(Table.java:29)
	at org.glavo.viewer.classfile.ClassFileComponent.read(ClassFileComponent.java:19)
	at org.glavo.viewer.classfile.ClassFileComponent.readContent(ClassFileComponent.java:31)
	at org.glavo.viewer.classfile.ClassFileComponent.read(ClassFileComponent.java:19)
	at org.glavo.viewer.classfile.datatype.Table.readAttributeInfo(Table.java:52)
	at org.glavo.viewer.classfile.datatype.Table.readEntry(Table.java:38)
	at org.glavo.viewer.classfile.datatype.Table.readContent(Table.java:29)
	at org.glavo.viewer.classfile.ClassFileComponent.read(ClassFileComponent.java:19)
	at org.glavo.viewer.classfile.ClassFileComponent.readContent(ClassFileComponent.java:31)
	at org.glavo.viewer.classfile.ClassFileComponent.read(ClassFileComponent.java:19)
	at org.glavo.viewer.classfile.ClassFileParser.parse(ClassFileParser.java:11)
	at org.glavo.viewer.gui.filetypes.classfile.ClassFileType.open(ClassFileType.java:38)
	at org.glavo.viewer.gui.OpenFileTask.call(OpenFileTask.java:35)
	at org.glavo.viewer.gui.OpenFileTask.call(OpenFileTask.java:13)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Glavo** [comment]
确认 bug 原因是 openjdk 9 测试版编译 module-info.java 文件时生成不符合规范的 class 文件
